---
- name: Home work 1 (Установка Docker, запуск wordpress и mysql)
  hosts: webserver
  become: true
  vars_files:
    - vars.yml
  pre_tasks:
    - name: Display Configuration Variables
      ansible.builtin.debug:
        msg:
          - "wordpress: {{ is_wordpress }}" # True or False
          - "wordpress_port: {{ wordpress_port }}" # 80 or 8080 or whatewer
          - "wordpress_db_name: {{ mysql_database }}" # WP database name
          - "db_host: {{ db_host }}" # container name CHANGE
          - "db_pass: {{ mysql_root_password }}" # root password
  roles:
    - role: initial
    - role: wp_with_db
